insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('coming-soon', 'placeholder', 'Coming Soon', '', 'coming-soon.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('coming-soon-with-lab', 'placeholder', 'Coming Soon', '', 'coming-soon.pdf', 'coming-soon.pdf', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('90-more-information', 'more', 'Course Introduction', '','90-more-information.pdf','', '');

insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('03-pcf-primer', 'pcf-general', 'Pivotal Cloud Foundry Overview', '', 'scdf/03-PCF-Primer.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('monitoring-logging', 'pcf-general', 'Moniting and Logging', '', 'monitoring-logging.pdf', 'monitoring-logging/index.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('patching-upgrading', 'pcf-general', 'Patching and Upgrading', '', 'patching-upgrading.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('security-topics', 'pcf-general', 'Security Topics', '', 'security.pdf', '', '');

insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('the-platform-for-a-new-way-of-working', 'pcf-general', 'The Platform for a New Way of Working', '', 'the-platform-for-a-new-way-of-working.pdf', '', '');

insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('a-new-way-of-working', 'transformation', 'A New Way of Working', '', 'a-new-way-of-working.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('an-open-ecosystem-of-services', 'transformation', 'An Open Ecosystem of Services', '', 'an-open-ecosystem-of-services.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('api-first', 'transformation', 'API First', '', 'api-first.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('becoming-cloud-native', 'transformation', 'Becoming Cloud Native', '', 'becoming-cloud-native.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('cloud-native-architecture', 'transformation', 'Cloud Native Architecutre', '', 'cloud-native-architecture.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('design-for-failure', 'transformation', 'Design for Failure', '', 'design-for-failure.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('enabling-cloud-native', 'transformation', 'Enabling a Cloud Native Organization', '', 'enabling-cloud-native.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('legacy-migration-to-cloud', 'transformation', 'Legacy Migration to the Cloud', '', 'legacy-migration-to-cloud.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('new-applications', 'transformation', 'Legacy Migration to the Cloud', '', 'new-applications.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('twelve-factor-apps', 'transformation', '12 Factor Applications', '', 'twelve-factor-apps.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('twelve-factor-apps-and-beyond', 'transformation', '12 Factor Applications (and Beyond)', '', 'twelve-factor-apps-and-beyond.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('what-is-cloud-native', 'transformation', 'What is a Cloud Native Application?', '', 'what-is-cloud-native.pdf', '', '');

insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('80a-cs-spring-boot-condensed', 'dellemc', 'Spring Boot', '','80a-cs-spring-boot-condensed.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('85a-spring-cloud-condensed', 'dellemc', 'Spring Cloud Services', '','85a-cs-spring-cloud-condensed.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('a-new-way-of-working-dell', 'dellemc', 'A New Way of Working', '', 'a-new-way-of-working-dell.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('dell-it-cloud-foundry', 'dellemc', 'Leveraging Dell IT Cloud Foundry', '','dell-it-cloud-foundry.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('steeltoe-and-dotnet', 'dellemc', '.NET and Steeltoe', '','dotnet-and-steeltoe.pdf', '', '');

insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('ci-dojo-video', 'liberty-mutual', 'Application Modernization in Commercial Insurance', '', '', '', 'https://liberty-videos.cfapps.io/engagements/ci-modernization-dojo.mp4');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('cio-diversification-video', 'liberty-mutual', 'Tech and Diversification of Risk', '', '', '', 'https://liberty-videos.cfapps.io/cio-interviews/diversification-of-risk.mp4');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('cio-faster-video', 'liberty-mutual', 'How to Move Faster', '', '', '', 'https://liberty-videos.cfapps.io/cio-interviews/how-to-move-faster.mp4');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('cio-innovation-video', 'liberty-mutual', 'Spurring Innovation at a Large Company', '', '', '', 'https://liberty-videos.cfapps.io/cio-interviews/spurring-innovation.mp4');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('cio-partnerships-video', 'liberty-mutual', 'In the Best Partnerships Everyone Wins', '', '', '', 'https://liberty-videos.cfapps.io/cio-interviews/partnerships.mp4');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('cio-trust-video', 'liberty-mutual', 'Establishing a Foundation of Trust with a Business', '', '', '', 'https://liberty-videos.cfapps.io/cio-interviews/foundation-of-trust.mp4');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('cio-urgency-video', 'liberty-mutual', 'The Urgency Behind Transformational Change', '', '', '', 'https://liberty-videos.cfapps.io/cio-interviews/urgency-behing-transformation.mp4');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('cloudforge-overview', 'liberty-mutual', 'CloudForge', '', 'https://liberty-content.cfapps.io/cloudforge-overview.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('deploying-to-cloudforge', 'liberty-mutual', 'Deploying with CloudForge', '', '', 'https://forge.lmig.com/wiki/display/STAC/Workshop+Lab+Instructions+Using+Eclipse#WorkshopLabInstructions-Lab2:Deployingasimpleapplicationthroughapipeline', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('cloudforce-services', 'liberty-mutual', 'Cloud Forge Services', '', 'https://liberty-content.cfapps.io/cloud-native.pdf', 'https://forge.lmig.com/wiki/display/STAC/Workshop+Lab+Instructions+Using+Eclipse#WorkshopLabInstructions-Lab3:Simplebindingtoservices', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('cloudforge-bluegreen', 'liberty-mutual', 'Blue-Green Deployment to CloudForge', '', '', 'https://forge.lmig.com/wiki/display/STAC/Workshop+Lab+Instructions+Using+Eclipse#WorkshopLabInstructions-Lab4:Thevalueofblue/greendeployments', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('cloudforge-network-access', 'liberty-mutual', 'Network Access on CloudForge', '', '', 'https://forge.lmig.com/wiki/display/STAC/Workshop+Lab+Instructions+Using+Eclipse#WorkshopLabInstructions-Lab5:UsingNetworkAccessTool', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('cloudforge-encryption', 'liberty-mutual', 'Encryption with CloudForge', '', '', 'https://forge.lmig.com/wiki/display/STAC/Workshop+Lab+Instructions+Using+Eclipse#WorkshopLabInstructions-Lab6:Bindinganencryptionservice', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('design-for-failure-with-lab', 'liberty-mutual', 'Design for Failure', '', 'design-for-failure.pdf', 'coming-soon.pdf', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('ets-labs-video', 'liberty-mutual', 'Build the Pipeline Provisioner Product in ETS', '', '', '', 'https://liberty-videos.cfapps.io/engagements/ets-provisioner-labs.mp4');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('gs-labs-video', 'liberty-mutual', 'Bringing a New Product to Market in Global Speciality', '', '', '', 'https://liberty-videos.cfapps.io/engagements/gs-australia-labs.mp4');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('moto-pairing-video', 'liberty-mutual', '"I Buy Motorcycle" Pairing Experience', '', '', '', 'https://liberty-videos.cfapps.io/engagements/moto/pairing.mp4');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('moto-product-video', 'liberty-mutual', 'Lean "I Buy Motorcycle" Lean Product Development', '', '', '', 'https://liberty-videos.cfapps.io/engagements/moto/lean-product.mp4');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('moto-team-video', 'liberty-mutual', 'The Balanced Team for "I Buy Motorcycle"', '', '', '', 'https://liberty-videos.cfapps.io/engagements/moto/balanced-team.mp4');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('moto-path-video', 'liberty-mutual', '"I Buy Motorcycle" Path to Production', '', '', '', 'https://liberty-videos.cfapps.io/engagements/moto/path-to-production.mp4');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('moto-path-video', 'liberty-mutual', '"I Buy Motorcycle" Path to Production', '', '', '', 'https://liberty-videos.cfapps.io/mojgan-cf-summit-2017.mp4');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('sample-application', 'liberty-mutual', 'A Sample Cloud-Native Application', '', '', 'https://forge.lmig.com/wiki/display/STAC/Workshop+Lab+Instructions+Using+Eclipse#WorkshopLabInstructions-Lab1:ExperienceCloudForge:useanexistingappandpipeline', '');

insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('cloud-native-applications', 'liberty-mutual', 'Cloud Native Applications', '', 'https://liberty-content.cfapps.io/cloud-native-applications.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('microservices-short', 'liberty-mutual', 'Microservices', '', '', 'https://forge.lmig.com/wiki/display/STAC/Workshop+Lab+Instructions+Using+Eclipse#WorkshopLabInstructionsUsingEclipse-Lab1:SpringInitializer', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('what-is-cloudforge', 'liberty-mutual', 'What is CloudForge?', '', 'https://liberty-content.cfapps.io/what-is-cloudforge.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('health-lab', 'liberty-mutual', 'Health Management in Cloud Foundry', '', '', 'https://forge.lmig.com/wiki/display/STAC/Workshop+Lab+Instructions+Using+Eclipse#WorkshopLabInstructionsUsingEclipse-Lab2:ObservingCloudFoundryHealthManagment', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('conventions', 'liberty-mutual', 'Conventions and Blueprints', '', 'https://liberty-content.cfapps.io/conventions-blueprints.pdf', 'https://forge.lmig.com/wiki/display/STAC/Workshop+Lab+Instructions+Using+Eclipse#WorkshopLabInstructionsUsingEclipse-Lab3:Deployingasimpleapplicationthroughyourownpipeline', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('more-reasons-cloudforge', 'liberty-mutual', 'More Reasons to Love CloudForge', '', 'https://liberty-content.cfapps.io/more-reasons.pdf', 'https://forge.lmig.com/wiki/display/STAC/Workshop+Lab+Instructions+Using+Eclipse#WorkshopLabInstructionsUsingEclipse-Lab5:Thevalueofblue/greendeployments', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('12-factor-detailed', 'liberty-mutual', 'Twelve Factor Applications', '', 'https://liberty-content.cfapps.io/12-factor.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('liberty-twelve-factor-quiz', 'liberty-mutual', 'A Quiz in Twelve Factors', '', 'https://cloud-native-workshop-development.us-east-1.np.paas.lmig.com/advanced-cloudforge/public/', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('cloudforge-services', 'liberty-mutual', 'Services Available', '', 'https://liberty-content.cfapps.io/services.pdf', 'https://forge.lmig.com/wiki/display/STAC/Workshop+Lab+Instructions+Using+Eclipse#WorkshopLabInstructionsUsingEclipse-Lab4:Simplebindingtoservices', '')
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('cloudforge-security', 'liberty-mutual', 'Security', '', 'https://liberty-content.cfapps.io/security.pdf', 'https://forge.lmig.com/wiki/display/STAC/Workshop+Lab+Instructions+Using+Eclipse#WorkshopLabInstructionsUsingEclipse-Lab6:UsingNetworkAccessTool', '')
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('becoming', 'liberty-mutual', 'Becoming Cloud Native', '', 'https://liberty-content.cfapps.io/becoming-cloud-native.pdf', '', '')
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('appcontinuum', 'liberty-mutual', 'The Application Continuum', '', 'https://deck.appcontinuum.io', 'https://github.com/barinek/appcontinuum', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('liberty-cloud-adoption', 'liberty-mutual', 'Cloud Adoption', '', 'https://liberty-content.cfapps.io/cloud-adoption.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('curfew', 'liberty-mutual', 'Reducing Costs with Curfew', '', '', 'https://forge.lmig.com/wiki/display/STAC/Workshop+Lab+Instructions+Using+Eclipse#WorkshopLabInstructionsUsingEclipse-Lab8:Reducingcostswithcurfew', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('exploring-12-factors', 'liberty-mutual', 'Exploring the 12 Factors', '', '', ' https://forge.lmig.com/wiki/display/STAC/Workshop+Lab+Instructions+Using+Eclipse#WorkshopLabInstructionsUsingEclipse-Lab9:Makeitbetter-cloudnativefactors', '');


insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('00-introduction', 'appdev', 'Course Introduction', '','00-introduction.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('02-intro-to-pcf', 'appdev', 'Overview of PCF', '', '02-intro-to-pcf.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('04-cli', 'appdev', 'Command Line Interface (CLI) intro', '','04-cli.pdf', 'labs/04-lab-cli.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('06-org-space-user-role', 'appdev', 'Orgs, Spaces, Users, Roles', '', '06-org-space-user-role.pdf','labs/06-lab-org-space-user-role.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('08-deploy-simple-app', 'appdev', 'Deploy a Simple Application', '', '08-deploy-simple-app.pdf', 'labs/08-lab-deploy-simple-app.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('10-application-manifest', 'appdev', 'Deployment Manifest Intro', '', '10-application-manifest.pdf', 'labs/10-lab-application-manifest.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('12-domains-and-routes', 'appdev', 'Domains and Routes', '', '12-domains-and-routes.pdf','labs/12-lab-domains-and-routes.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('14-services', 'appdev', 'Services Intro', '', '14-services.pdf', 'labs/14-lab-services.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('20a-opsmgr-and-bosh-short', 'appdev', 'BOSH Brief Intro', '', '20a-opsmgr-and-bosh-short.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('26-elastic-runtime', 'appdev', 'Elastic Runtime Architecture', '', '26-elastic-runtime.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('40-high-availability', 'appdev', 'High Availability', '', '40-high-availability.pdf', '', '');


insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('66-continuous-delivery', 'cna', 'Continuous Deliver', '','66-continuous-delivery.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('68-cloud-native-design', 'cna', 'Cloud Native Design', '', '68-cloud-native-design.pdf','', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('70-microservices', 'cna', 'Microservices', '', '70-microservices.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('cna-culture-changes-slides', 'cna', 'Cloud Native Changes', '', '64-cna-changes.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('why-cloud-native-slides', 'cna', 'Why Build Cloud Native Applications', '','63-why-cloud-native-apps.pdf','', '');

insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('56-cloud-controller-API', 'customization', 'Cloud Controller API', '','56-cloud-controller-API.pdf','', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('58-service-broker', 'customization', 'Service Brokers', '', '58-service-brokers.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('59-oauth-primer', 'customization', 'OAuth Primer', '','59-oauth-primer.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('60-security-and-sso', 'customization', 'Security and SSO', '', '60-security-and-sso.pdf','', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('62-buildpacks', 'customization', 'Buildpacks', '', '62-buildpacks.pdf', '', '');

insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('80-cs-spring-boot-basics', 'boot', 'Spring Boot Basics', '','80-cs-spring-boot-basics.pdf', 'labs/80-spring-boot-basics-lab.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('82-cs-spring-boot-adv', 'boot', 'Spring Boot Going Further', '', '82-cs-spring-boot-adv.pdf','labs/82-cs-spring-boot-adv-lab.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('actuator', 'boot', 'Spring Boot Actuator', '', '83-spring-boot-actuator.pdf', 'labs/83-spring-boot-primer-actuator-lab.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('spring-boot-labs-setup', 'boot', 'Lab Setup', '', '', 'labs/Spring Boot Labs Setup.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('spring-boot-requirements', 'boot', 'Lab Requirements', '','','/spring-boot-primer/requirements', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('spring-data-rest', 'boot', 'Spring Boot with Spring Data Rest', '', '84-spring-data-rest.pdf', 'labs/84-spring-data-rest-lab.html', '');




insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf-developer-apm', 'pcf-developer-advanced', 'Application Performance Monitoring', '', '', 'pivotal-cloud-foundry-developer/pcf-developer-advanced/application-performance-monitor/index.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf-developer-autoscaling', 'pcf-developer-advanced', 'Application Autoscaling', '', '', 'pivotal-cloud-foundry-developer/pcf-developer-advanced/application-auto-scaler/index.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf-developer-brokers', 'pcf-developer-advanced', 'Service Brokers', '', 'pivotal-cloud-foundry-developer/pcf-developer-advanced/service-broker/service-broker.pdf', 'pivotal-cloud-foundry-developer/pcf-developer-advanced/service-broker/index.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf-developer-cd', 'pcf-developer-advanced', 'Continuous Delivery', '', 'pivotal-cloud-foundry-developer/pcf-developer-advanced/continuous-delivery/continuous-delivery.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf-developer-log-asg', 'pcf-developer-advanced', 'Application Security Groups', '', 'pivotal-cloud-foundry-developer/pcf-developer-advanced/application-security-group/application-security-group.pdf', 'pivotal-cloud-foundry-developer/pcf-developer-advanced/application-security-group/index.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf-developer-log-drain', 'pcf-developer-advanced', 'Log Drain', '', 'pivotal-cloud-foundry-developer/pcf-developer-advanced/log-drain/log-drain.pdf', 'pivotal-cloud-foundry-developer/pcf-developer-advanced/log-drain/index.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf-developer-route-services', 'pcf-developer-advanced', 'Route Services', '', 'pivotal-cloud-foundry-developer/pcf-developer-advanced/route-service/route-service.pdf', 'pivotal-cloud-foundry-developer/pcf-developer-advanced/route-service/index.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf-developer-buildpacks', 'pcf-developer-basic', 'Buildpacks', '', 'pivotal-cloud-foundry-developer/pcf-developer-basics/buildpack/buildpack.pdf', 'pivotal-cloud-foundry-developer/pcf-developer-basics/buildpack/index.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf-developer-logging-scale-ha', 'pcf-developer-basic', 'Logging, Scale, and High Availability', '', 'pivotal-cloud-foundry-developer/pcf-developer-basics/logging-scale-ha/logging-scale-ha.pdf', 'pivotal-cloud-foundry-developer/pcf-developer-basics/logging-scale-ha/index.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf-developer-manifests', 'pcf-developer-basic', 'Manifests', '', '', 'pivotal-cloud-foundry-developer/pcf-developer-basics/manifest/index.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf-developer-org-spaces-roles', 'pcf-developer-basic', 'Orgs, Spaces, Roles', '', 'pivotal-cloud-foundry-developer/pcf-developer-basics/orgs-spaces-roles/orgs-spaces-roles.pdf', 'pivotal-cloud-foundry-developer/pcf-developer-basics/orgs-spaces-roles/index.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf-developer-push', 'pcf-developer-basic', 'Push to the Cloud', '', 'pivotal-cloud-foundry-developer/pcf-developer-basics/cf-push-to-the-cloud/intro.pdf', 'pivotal-cloud-foundry-developer/pcf-developer-basics/cf-push-to-the-cloud/index.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf-developer-services', 'pcf-developer-basic', 'Services', '', 'pivotal-cloud-foundry-developer/pcf-developer-basics/services/services.pdf', 'pivotal-cloud-foundry-developer/pcf-developer-basics/services/index.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('blue-green-deployments', 'pcf-developer-previous', 'Blue-Green Deployments', '', 'resources/presentations/blue-green.pdf', 'blue-green/index.html', '');


insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf101-session1-cne', 'pcf101', 'Welcome to the Cloud Native Enterprise', '','Session_1_Cloud_Native_Enterprise.pdf','', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf101-session2-arch', 'pcf101', 'Pivotal Cloud Foundry Architecture and Containers', '','Session_2_Architecture.pdf','', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf101-session2a-oper', 'pcf101', 'Pivotal Cloud Foundry Operations', '','Session_2a_Operations.pdf','', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf101-session3-services', 'pcf101', 'Pivotal Cloud Foundry Services', '','Session_3_Services_Overview.pdf','', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf101-lab1', 'pcf101', 'Lab 1 - From Zero to Pushing Your First Application', '','','labs/pcf101/lab1/lab.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf101-lab1-node', 'pcf101', 'Lab 1 - From Zero to Pushing Your First Application', '','','labs/pcf101/lab1/lab-node.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf101-lab1-ruby', 'pcf101', 'Lab 1 - From Zero to Pushing Your First Application', '','','labs/pcf101/lab1/lab-ruby.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf101-lab2', 'pcf101', 'Lab 2 - Binding to Cloudfoundry Services', '','','labs/pcf101/lab2/lab.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf101-lab3', 'pcf101', 'Lab 3 - Operating your Application', '','','labs/pcf101/lab3/lab.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf101-lab4', 'pcf101', 'Lab 4 - Monitoring your Application', '','','labs/pcf101/lab4/lab.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('pcf101-lab5', 'pcf101', 'Lab 5 - Deploying a .NET Application', '','','labs/pcf101/lab5/lab.html', '');

insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('00-agenda-and-logistics', 'scdf', 'Agenda and Logistics', '', 'scdf/00-AgendaAndLogistics.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('02-architecture', 'scdf', 'Architecture', '', 'scdf/02-Architecture.pdf', 'scdf/labs/installation-cf.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('03-pcf-primer', 'scdf', 'PCF Primer', '', 'scdf/03-PCF-Primer.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('04-introduction-streams', 'scdf', 'Introduction to Streams', '', 'scdf/04-IntroductionToStreams.pdf', 'scdf/labs/introduction-to-streams.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('05-advanced-streams', 'scdf', 'Advanced Streams', '', 'scdf/05-AdvancedStreams.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('06-boot-primer', 'scdf', 'Spring Boot Primer', '', 'scdf/06-SpringBootPrimer.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('07-introduction-jobs', 'scdf', 'Introduction to Jobs', '', 'scdf/07-IntroductionToJobs', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('07-spring-cloud-stream', 'scdf', 'Spring Cloud Stream', '', 'scdf/07-SpringCloudStream', 'scdf/labs/spring-cloud-stream-local.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('08-customizing', 'scdf', 'Customizing Job Modules', '', 'scdf/08-CustomizingJobModules.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('09-advanced-jobs', 'scdf', 'Advanced Jobs', '', 'scdf/09-AdvancedJobs.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('09-spring-cloud-tasks', 'scdf', 'Tasks', '', 'scdf/09-SpringCloudTasks.pdf', 'scdf/labs/spring-cloud-custom-task-local.html, ''', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('10-distributed-mode', 'scdf', 'Distributed Mode', '', 'scdf/10-DistributedMode.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('11-high-availability', 'scdf', 'High Availability', '', 'scdf/11-High-Availability.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('12-management-monitoring', 'scdf', 'Management and Monitoring', '', 'scdf/12-ManagementAndMonitoring.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('15-analytics', 'scdf', 'Analytics', '', 'scdf/15-Analytics.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('21-ha-appendix', 'scdf', 'High Availability (Appendix)', '', 'scdf/21-HighAvailability-Appendix.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('60-migration', 'scdf', 'Migration', '', 'scdf/60-Migration.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('data-microservices', 'scdf', 'Data Microservices', '', 'data-microservices.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('data-microservices-pcf', 'scdf', 'Data Microservices', '', 'data-microservices-pcf.pdf', '', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('springcloud-dataflow', 'scdf', 'Spring Cloud Data Flow', '', 'springcloud_dataflow.pdf', '', '');

insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('circuit-breaker-metric-aggregation', 'scs', 'Spring Cloud Netflix - Circuit Breaker Metric Aggregation', '', '89-spring-cloud-netflix-circuit-breaker-metric-aggregation.pdf', 'labs/89-spring-cloud-netflix-circuit-breaker-metric-aggregation-lab.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('circuit-breakers', 'scs', 'Spring Cloud Netflix - Circuit Breakers', '', '88-spring-cloud-netflix-circuit-breakers.pdf', 'labs/88-spring-cloud-netflix-circuit-breakers-lab.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('client-slide-load-balancing', 'scs', 'Spring Cloud Netflix - Client Side Load Balancing', '', '87-spring-cloud-netflix-client-side-load-balancing.pdf', 'labs/87-spring-cloud-netflix-client-side-load-balancing-lab.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('config', 'scs', 'Spring Cloud Config', '','85-spring-cloud-config.pdf', 'labs/85-spring-cloud-config-lab.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('scs-labs-setup', 'scs', 'Lab Setup', '', '', 'labs/Spring Cloud Services Labs Setup.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('scs-requirements', 'scs', 'Lab Requirements', '','','/spring-cloud-services/requirements/index.html', '');
insert into content (courseID, section, title, description, slideURL, labURL, videoURL) values ('service-discovery', 'scs', 'Spring Cloud Netflix - Service Discovery', '', '86-spring-cloud-netflix-service-discovery.pdf','labs/86-spring-cloud-netflix-service-discovery-lab.html', '');
